kind: pipeline
name: default

steps:
  - name: build
    image: plugins/hugo
    settings:
      hugo_version: 0.74.3
      validate: true

  - name: deploy
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_hostname
      target: /srv/www.robot-disco.net
      source: public/*
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port:
        from_secret: ssh_port
      when:
        branch:
        - master
        event:
          exclude:
          - pull_request
 
